version: '3'
services:
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          memory: 512M

  price-service-db:
    image: timescale/timescaledb:latest-pg15
    container_name: price-service-db
    environment:
      POSTGRES_DB: market-price
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5431:5432
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - ./rts-exchange-gateway-processor/src/main/resources/db/schema:/docker-entrypoint-initdb.d
      - price_service_db_data:/var/lib/postgresql/data

  account-db:
    image: postgres:15
    container_name: account-service-db
    environment:
      POSTGRES_DB: account-service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: 512M
  rts-discovery-server:
    image: devops22clc/rts-discovery-server
    container_name: rts-discovery-server
    ports:
      - 8761:8761
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://discovery-server:8761"]
      interval: 5s
      timeout: 3s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 512M

  rts-api-gateway:
    image: devops22clc/rts-api-gateway
    container_name: rts-api-gateway
    ports:
      - 8080:8080
    depends_on:
      - rts-discovery-server
    deploy:
      resources:
        limits:
          memory: 512M


  rts-account-service:
    image: devops22clc/rts-account-service
    container_name: rts-account-service
    ports:
      - 8085:8085
    depends_on:
      - rts-discovery-server
    deploy:
      resources:
        limits:
          memory: 512M

  rts-payment-service:
    image: devops22clc/rts-payment-service
    container_name: rts-payment-service
    ports:
      - 8088:8088
    depends_on:
      - rts-discovery-server
    deploy:
      resources:
        limits:
          memory: 512M

  rts-price-service:
    image: devops22clc/rts-price-service
    container_name: rts-price-service
    ports:
      - 8083:8083
    depends_on:
      - rts-discovery-server
    deploy:
      resources:
        limits:
          memory: 512M

  rts-exchange-gateway-processor:
    image: devops22clc/rts-exchange-gateway-processor
    container_name: rts-exchange-gateway-processor
    ports:
      - 8082:8082
    depends_on:
      - rts-discovery-server
    deploy:
      resources:
        limits:
          memory: 512M

  rts-backtest-service:
    image: devops22clc/rts-backtest-service
    container_name: rts-backtest-service
    ports:
      - 8089:8089
    depends_on:
      - rts-discovery-server
    deploy:
      resources:
        limits:
          memory: 512M


volumes:
  price_service_db_data: