server:
  port: 8086

spring:
  application:
    name: backtest-service
  servlet:
    multipart:
      max-file-size: 50MB       # Giới hạn dung lượng 1 file
      max-request-size: 50MB
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:7080/realms/master/protocol/openid-connect/certs

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

# ===== THÊM MỚI: Cấu hình tùy chỉnh cho ứng dụng =====
app:
  # URL của price-service, được gọi thông qua API Gateway
  price-service-url: "http://localhost:8080/api/v1/price"
  model-storage-path: "./models"

---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

app:
  price-service-url: "http://api-gateway:8080/api/v1/price"
  model-storage-path: "/app/models"