spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5430/payment-service?sslmode=disable
    password: mysecretpassword
    username: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      connection-timeout: 30000
      pool-name: HikariPool

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        type:
          preferred_enum_type: pgsql
    show-sql: true

  sql:
    init:
      mode: always
      platform: postgres

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

endpoint:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  # standalone mode
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/

vnpay:
  tmn-code: "KJKB95LB"
  hash-secret: "VSF1LDNVK1RWT6HRN6Q93HFOTGTFPYV4"
  url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "http://localhost:5173/payment/callback"
keycloak:
  auth-server-url: http://localhost:7080
  realm: master
  admin:
    client-id: admin-cli
    client-secret: 7UDgUTaPN6mRMj1JwHaV4rUPkNgoHw3c
    username: admin
    password: admin
  vip-role-name: vip

frontend:
  url: "http://localhost:5173"
logging:
  level:
    org.springframework.jdbc: DEBUG
---

spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/