syntax = "proto3";

import "google/protobuf/timestamp.proto";

option java_multiple_files = true;
option java_outer_classname = "AccountProto";
option java_package = "com.radartrade.platform.server.gateway.grpc";

message Account {
    string owner = 1;
    int64 balance = 2;
    string currency = 3;
    google.protobuf.Timestamp created_at = 4;
}

message CreateAccountRequest {
    string owner = 1;
    int64 balance = 2;
    string currency = 3;
}

message CreateAccountResponse {
    Account account = 1;
}

message GetAccountByIdRequest {
    int64 id = 1;
}

message GetAccountByIdResponse {
    Account account = 1;
}

message GetAccountByOwnerRequest {
    string owner = 1;
}

message GetAccountByOwnerResponse {
    repeated Account account = 1;
}
