spring:
  application:
    name: exchange-gateway-processor
  config:
    activate:
      on-profile: default
  r2dbc:
    url: r2dbc:postgresql://localhost:5431/market-price?sslmode=disable
    password: mysecretpassword
    username: root
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

endpoint:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  # standalone mode
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/


exchange:
    api:
      rest:
        base-url: https://api.binance.com

my:
  runner:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: docker
  r2dbc:
    url: r2dbc:postgresql://price-service-db:5432/market-price?sslmode=disable
    username: root
    password: mysecretpassword
  data:
    redis:
      host: redis
      port: 6379
eureka:
  client:
    service-url:
      default-zone: http://rts-discovery-server:8761/eureka/